# Sales Records Analysis

### Author: Naomi Tewolde

### Exercise 2.E Using functions for analyzing data
This notebook analyzes a small sales dataset using Python functions.
Each function takes the full dataset as its first argument.

In [1]:
sales_data = [
 ('Laptop', 'East', 1200.00),
 ('Phone', 'West', 850.00),
 ('Tablet', 'East', 400.00),
 ('Monitor', 'South', 650.00),
 ('Keyboard', 'West', 75.00),
 ('Laptop', 'South', 1150.00),
 ('Phone', 'East', 900.00),
 ('Tablet', 'West', 425.00),
 ('Monitor', 'East', 680.00),
 ('Keyboard', 'South', 80.00),
 ('Laptop', 'West', 1300.00),
 ('Phone', 'West', 820.00),
]

## Lab 1. Total sales by region

In [2]:
def region_total(data, region):
    total = 0
    for product, r, amount in data:
        if r == region:
            total += amount
    return total

In [3]:
print(region_total(sales_data, 'East'))
print(region_total(sales_data, 'West'))
print(region_total(sales_data, 'South'))

3180.0
3470.0
1880.0


## Lab 2. Count of sales by region

In [4]:
def region_count(data, region):
    return sum(1 for product, r, amount in data if r == region)

In [5]:
print(region_count(sales_data, 'East'))
print(region_count(sales_data, 'West'))
print(region_count(sales_data, 'South'))

4
5
3


## Lab 3. Average sale amount by region

In [6]:
def region_average(data, region):
    total = region_total(data, region)
    count = region_count(data, region)
    
    if count == 0:
        return 0
    return total / count

In [7]:
print(region_average(sales_data, 'East'))
print(region_average(sales_data, 'West'))
print(region_average(sales_data, 'South'))

795.0
694.0
626.6666666666666


In [8]:
print(region_average(sales_data, 'North'))

0


## Lab 4. Filter by sale amount

In [9]:
def sales_above(data, threshold):
    return [record for record in data if record[2] > threshold]

In [10]:
results = sales_above(sales_data, 500)

In [11]:
for record in results:
    print(record)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


## Lab 5. Top and bottom sale

In [12]:
def top_sale(data):
    return max(data, key=lambda record: record[2])

In [13]:
def bottom_sale(data):
    return min(data, key=lambda record: record[2])

In [14]:
print(top_sale(sales_data))
print(bottom_sale(sales_data))

('Laptop', 'West', 1300.0)
('Keyboard', 'West', 75.0)


### RESULT SUMMARY 

The top sale was a Laptop in the West region for 1300.00
The lowest sale was a keyboard in the West region for 75.00

## Lab 6. Apply a discount

In [15]:
def apply_discount(data, discount_pct):
    return list(map(lambda s: (s[0], s[1], s[2] * (1 - discount_pct)), data))

In [16]:
discounted_sales = apply_discount(sales_data, 0.10)

In [17]:
for record in discounted_sales:
    print(record)

('Laptop', 'East', 1080.0)
('Phone', 'West', 765.0)
('Tablet', 'East', 360.0)
('Monitor', 'South', 585.0)
('Keyboard', 'West', 67.5)
('Laptop', 'South', 1035.0)
('Phone', 'East', 810.0)
('Tablet', 'West', 382.5)
('Monitor', 'East', 612.0)
('Keyboard', 'South', 72.0)
('Laptop', 'West', 1170.0)
('Phone', 'West', 738.0)


### Trying 15% discount

In [18]:
discounted_sales_15 = apply_discount(sales_data, 0.15)

In [19]:
print("Original (first 3):")
for record in sales_data[:3]:
    print(record)

Original (first 3):
('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Tablet', 'East', 400.0)


In [20]:
print("\nAfter 15% discount (first 3):")
for record in discounted_sales_15[:3]:
    print(record)


After 15% discount (first 3):
('Laptop', 'East', 1020.0)
('Phone', 'West', 722.5)
('Tablet', 'East', 340.0)


## Lab 7. Unique regions

In [21]:
def unique_regions(data):
    return sorted(set(region for product, region, amount in data))

In [22]:
print(unique_regions(sales_data))

['East', 'South', 'West']


### Analysis
The unique_regions function helps find all distinct regions in the data.  
This is useful for grouping, filtering, or running analysis (like totals or averages)
for each region without hardcoding names.


## Lab 8. Region summary

In [23]:

def region_summary(data, region):
    total = region_total(data, region)
    count = region_count(data, region)
    average = region_average(data, region)
    
    region_data = [record for record in data if record[1] == region]
    
    top = top_sale(region_data) if region_data else None
    
    # Print formatted report
    print(f"=== {region} Region ===")
    print(f"Records: {count}")
    print(f"Total Sales: ${total:,.2f}")
    print(f"Average Sale: ${average:,.2f}")
    
    if top:
        print(f"Top Sale: {top[0]} — ${top[2]:,.2f}")
    else:
        print("Top Sale: None")


In [24]:
region_summary(sales_data, 'East')
region_summary(sales_data, 'West')
region_summary(sales_data, 'South')

=== East Region ===
Records: 4
Total Sales: $3,180.00
Average Sale: $795.00
Top Sale: Laptop — $1,200.00
=== West Region ===
Records: 5
Total Sales: $3,470.00
Average Sale: $694.00
Top Sale: Laptop — $1,300.00
=== South Region ===
Records: 3
Total Sales: $1,880.00
Average Sale: $626.67
Top Sale: Laptop — $1,150.00


## Lab 9. Full summary 

In [26]:
for r in unique_regions(sales_data):
    region_summary(sales_data, r)
    print()  # blank line for readability

=== East Region ===
Records: 4
Total Sales: $3,180.00
Average Sale: $795.00
Top Sale: Laptop — $1,200.00

=== South Region ===
Records: 3
Total Sales: $1,880.00
Average Sale: $626.67
Top Sale: Laptop — $1,150.00

=== West Region ===
Records: 5
Total Sales: $3,470.00
Average Sale: $694.00
Top Sale: Laptop — $1,300.00



### Reflection: 
In this lab, I learned how to use functions to organize and reuse code for data analysis. 
I practiced working with lists, tuples, and lambda functions, and used tools like map(), 
list comprehensions, and generator expressions to process data efficiently.

I also learned how to calculate totals, counts, averages, and filter data, as well as how 
to create clean summaries. Overall, this lab helped me understand how to structure code 
for real-world data analysis tasks.